title: "Kyle Schmitt — GIS Portfolio"
description: "Maps and spatial analysis for Urban Planning"
baseurl: ""
url: "https://kschmitt0.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed

# Files/folders Jekyll should ignore when building
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
